MAIN_LINK = "https://knigosklad.com.ua/ua/"
TEST_EMAIL = "bereza.olena@gmail.com"
PASSWORD = "wBVU6erRwWzb5mE"
IMPLICITLY_WAIT = 10
EXPLICITLY_WAIT = 10
TEST_NAME = "KATE"
TEST_LASTNAME = "SMITH"
TEST_PHONE = "(067) 111-11-11"
SEARCH = "СЛОН"